package View;
import Controller.UsuarioCadastro;
import Model.DAO.Banco;
import javax.swing.JTextField;
import Controller.Helpers.UsuarioCadastroHelper;
/**
 *
 * @author mathe
 */
public class cadastroUser extends javax.swing.JFrame {

    private final UsuarioCadastro controller;
    private final UsuarioCadastroHelper controller1;
    
    
    public cadastroUser() {
        initComponents();
        this.controller = new UsuarioCadastro(this);
        this.controller1 = new UsuarioCadastroHelper(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextTipo = new javax.swing.JTextField();
        TextId = new javax.swing.JTextField();
        nomeText = new javax.swing.JTextField();
        TextDataCad = new javax.swing.JTextField();
        TextCPF = new javax.swing.JTextField();
        btnCadUser = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TextEnder = new javax.swing.JTextField();
        PlanoDeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Uni Neue Heavy", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Tipo de Usuário:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Uni Neue Heavy", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Uni Neue Heavy", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("Data Cadastro:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 700, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Uni Neue Heavy", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("CPF:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Uni Neue Heavy", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setText("Endereço:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        TextTipo.setBackground(new java.awt.Color(255, 255, 255));
        TextTipo.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(TextTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 610, 900, 40));

        TextId.setBackground(new java.awt.Color(255, 255, 255));
        TextId.setForeground(new java.awt.Color(0, 0, 0));
        TextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIdActionPerformed(evt);
            }
        });
        getContentPane().add(TextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 80, 40));

        nomeText.setBackground(new java.awt.Color(255, 255, 255));
        nomeText.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(nomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 900, 40));

        TextDataCad.setBackground(new java.awt.Color(255, 255, 255));
        TextDataCad.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(TextDataCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 700, 900, 40));

        TextCPF.setBackground(new java.awt.Color(255, 255, 255));
        TextCPF.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(TextCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 900, 40));

        btnCadUser.setBackground(new java.awt.Color(0, 51, 255));
        btnCadUser.setFont(new java.awt.Font("Uni Neue Heavy", 0, 14)); // NOI18N
        btnCadUser.setForeground(new java.awt.Color(255, 255, 255));
        btnCadUser.setText("ENVIAR");
        btnCadUser.setBorderPainted(false);
        btnCadUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 790, 160, 50));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Uni Neue Heavy", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Nome Completo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        TextEnder.setBackground(new java.awt.Color(255, 255, 255));
        TextEnder.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(TextEnder, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 900, 40));

        PlanoDeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/cadastroUser.png"))); // NOI18N
        getContentPane().add(PlanoDeFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1378, 916));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUserActionPerformed
            this.controller.cadastrarUsuario();
    }//GEN-LAST:event_btnCadUserActionPerformed

    private void TextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PlanoDeFundo;
    private javax.swing.JTextField TextCPF;
    private javax.swing.JTextField TextDataCad;
    private javax.swing.JTextField TextEnder;
    private javax.swing.JTextField TextId;
    private javax.swing.JTextField TextTipo;
    private javax.swing.JButton btnCadUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nomeText;
    // End of variables declaration//GEN-END:variables


}

